kind: pipeline
name: formatting

workspace:
  base: /go
  path: src/github.com/jsimonetti/go-spice

steps:
  - name: fmt
    image: golang
    commands:
      - export GOFMT=$(gofmt -l .)
      - echo -n "$GOFMT"
      - $(exit $(echo -n "$GOFMT" | wc -c))
  - name: dep
    image: golang
    commands:
      - go get github.com/golang/dep/...
      - dep ensure
  - name: vet
    image: golang
    commands:
      - go vet ./...

when:
  event:
    - push


---
kind: pipeline
name: optional

workspace:
  base: /go
  path: src/github.com/jsimonetti/go-spice

steps:
  - name: lint
    image: golang
    err_ignore: true
    commands:
      - go get golang.org/x/lint/golint
      - export GOLINT=$(golint ./... | grep --invert-match -P "(_string.go:)")
      - echo "$GOLINT"
      - $(exit $(echo -n "$GOLINT" | wc -c))

trigger:
  status:
    - success

depends_on:
  - formatting

---
kind: pipeline
name: tests

workspace:
  base: /go
  path: src/github.com/jsimonetti/go-spice

steps:
  - name: dep
    image: golang
    commands:
      - go get github.com/golang/dep/...
      - dep ensure
  - name: test
    image: golang
    commands:
      - go test -v ./...
  - name: integration
    image: golang
    privileged: true
    commands:
      - go test -v -tags=integration ./...

when:
  event:
    - push
